name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        platform: ['amd64', 'arm64']
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build with Docker
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/${{ matrix.platform }}
          outputs: type=tar,dest=../out.tar

      - name: Extract built rTorrent binaries from Docker image
        run: |
          tar xvf ../out.tar usr/local/bin/rtorrent

      - uses: actions/upload-artifact@v2
        with:
          name: rtorrent-static-linux-${{ matrix.platform }}
          path: usr/local/bin/rtorrent
