name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  docker:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Publish to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            jesec/rtorrent:latest
            jesec/rtorrent:master

      - name: Extract built rTorrent binaries from Docker images
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -o type=tar . > ../out.tar
          tar xvf ../out.tar linux_amd64/usr/local/bin/rtorrent linux_arm64/usr/local/bin/rtorrent

      - uses: actions/upload-artifact@v2
        with:
          name: rtorrent-static-linux-amd64
          path: linux_amd64/usr/local/bin/rtorrent

      - uses: actions/upload-artifact@v2
        with:
          name: rtorrent-static-linux-arm64
          path: linux_arm64/usr/local/bin/rtorrent

      - run: |
          mv linux_amd64/usr/local/bin/rtorrent rtorrent-linux-amd64
          mv linux_arm64/usr/local/bin/rtorrent rtorrent-linux-arm64

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ steps.get_version.outputs.VERSION }}
          files: |
            rtorrent-linux-amd64
            rtorrent-linux-arm64
            doc/rtorrent.rc
