name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  docker:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Tag release
        run: |
          release=`echo ${{ steps.get_version.outputs.VERSION }} | cut -d'-' -f2`
          sed s/-jc+master/-jc-$release/ BUILD > BUILD.versioned
          cat BUILD.versioned
          mv BUILD.versioned BUILD

      - name: Set up QEMU
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Publish to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            jesec/rtorrent:latest

      - name: Extract built rTorrent artifacts from Docker image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 --target build -o type=tar . > ../out.tar
          tar xvf ../out.tar linux_amd64/root/rtorrent/dist linux_arm64/root/rtorrent/dist

      - run: |
          cp -L linux_amd64/root/rtorrent/dist/rtorrent rtorrent-linux-amd64
          cp -L linux_amd64/root/rtorrent/dist/rtorrent-deb.deb rtorrent-linux-amd64.deb
          cp -L linux_arm64/root/rtorrent/dist/rtorrent rtorrent-linux-arm64
          cp -L linux_arm64/root/rtorrent/dist/rtorrent-deb.deb rtorrent-linux-arm64.deb

      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: ${{ steps.get_version.outputs.VERSION }}
          files: |
            rtorrent-linux-amd64
            rtorrent-linux-amd64.deb
            rtorrent-linux-arm64
            rtorrent-linux-arm64.deb
            doc/rtorrent.rc
            doc/rtorrent@.service
